### hc
GET {{host}}/hc

### Create Task
POST {{host}}/task
Content-Type: application/json

{
  "language": "zh",
  "user_id": "cd345a58-2c40-4519-9533-d50a1e1b8238",
  "block_duration": 61,
  "creator": "lucky bot"
}

### Active Task
POST {{host}}/task/77/active

### Find Task
GET {{host}}/task/77

### Cancel Task
POST {{host}}/task/66/cancel

###

